on:
  push:
    branches:
    - main
jobs:
  check-create-repo:
    if: github.actor == 'lm-yang'
    strategy:
      matrix:
        region: [us-east-1]
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: Github-OIDC-Role-uaGL3MDzvfzm
      - name: Get secrets by name and by ARN
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            SECRET_IAD,arn:aws:secretsmanager:us-east-1:241580540779:secret:GITHUB_TOKENS/MASTER-u0Kqa1
      - name: Setup Github Credential
        run: |
          case "${{ matrix.region }}" in
            us-east-1)
              echo "ENV_SECRET=${SECRET_IAD}" >> $GITHUB_ENV
              ;;
          esac
      - name: Check if repo exists and create if not
        uses: actions/github-script@v5
        with:
          script: |
            const repoName = context.repo.repo;
            const owner = "bullet-dev-team-${{ matrix.region }}";
            try {
              await github.rest.repos.get({
                owner: owner,
                repo: repoName,
              });
              console.log("Repository exists");
            } catch (error) {
              if (error.status === 404) {
                console.log("Repository does not exist, creating...");
                await github.rest.repos.createForAuthenticatedUser({
                  name: repoName,
                  private: true
                });
                console.log("Repository created");
              } else {
                console.log("Error occurred while creating repository:", error);
              }
            }
          github-token: ${{ env.ENV_SECRET }}
