on:
  push:
    branches:
    - main
permissions:
    id-token: write
    contents: read
jobs:
  sync_repo_to_all_regions:
    if: github.actor == 'bullet-dev-team'
    strategy:
      matrix:
        region: [us-west-2, us-east-1, ap-northeast-1, ap-southeast-1, ap-southeast-2, eu-central-1, eu-west-1, us-east-2, eu-west-2, eu-west-3, ap-south-1]
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credential through OpenID connect
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::241580540779:role/Github-OIDC-Role-uaGL3MDzvfzm
      - name: Get Github Personal Access Tokens from Secret Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            SECRET,arn:aws:secretsmanager:us-east-1:241580540779:secret:GithubPAT-5w0tRn
          parse-json-secrets: true
      - name: Setup Github Personal Access Token
        run: |
          printenv
          region="${{ matrix.region }}"
          secret_name="SECRET_$(echo ${region} | tr 'a-z-' 'A-Z_' | tr - _)"
          echo "ENV_SECRET=${!secret_name}" >> ${GITHUB_ENV}
          echo "SECRET_MASTER=${SECRET_MASTER}" >> ${GITHUB_ENV}
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)" >> $GITHUB_ENV
          printenv
